---
title: "covid_19_analysis"
author: "Benji Edwards"
date: "`r Sys.Date()`"
output: github_document
---
Is state an indicator for COVID deaths?

# Import
Load R packages and data from Johns Hopkins COVID-19 repository. This data includes case reports from January 21, 2020 to March 10, 2023.
```{r Import}
# Load in R packages and data
library(tidyverse)

us_covid_cases <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")

us_covid_deaths <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")

```
#Inspect
Let's take a look at the data that we've imported.
```{r Inspect}

# US COVID cases
nrow(us_covid_cases)

head(us_covid_cases)

# US COVID deaths
nrow(us_covid_deaths)

head(us_covid_deaths)
```

# Tidy
Now let's tidy the data so it can be analyzed.
```{r Tidy}
us_cases_clean <- us_covid_cases %>%
  select(-c('Lat', 'Long_', 'UID', 'iso2', 'iso3', 'code3', 'FIPS', 'Country_Region', 'Combined_Key'))
us_cases_clean <-  us_cases_clean %>%
  pivot_longer(cols = -c('Admin2', 'Province_State'),
               names_to = "date",
               values_to = "cases")
us_cases_clean
```

